version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - RABBITMQ_HOST=lunar.sekawan.co.id
      - RABBITMQ_PORT=6015
      - RABBITMQ_USER=developer
      - RABBITMQ_PASSWORD=sekawan
    depends_on:
      - email-worker
      - scheduler-worker

  email-worker:
    build:
      context: .
      dockerfile: workers/Dockerfile.email
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - RABBITMQ_HOST=lunar.sekawan.co.id
      - RABBITMQ_PORT=6015
      - RABBITMQ_USER=developer
      - RABBITMQ_PASSWORD=sekawan

  scheduler-worker:
    build:
      context: .
      dockerfile: workers/Dockerfile.scheduler
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - RABBITMQ_HOST=lunar.sekawan.co.id
      - RABBITMQ_PORT=6015
      - RABBITMQ_USER=developer
      - RABBITMQ_PASSWORD=sekawan

  analytics-worker:
    build:
      context: .
      dockerfile: workers/Dockerfile.analytics
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - RABBITMQ_HOST=lunar.sekawan.co.id
      - RABBITMQ_PORT=6015
      - RABBITMQ_USER=developer
      - RABBITMQ_PASSWORD=sekawan
    depends_on:
      - app