# workers/Dockerfile.email
FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY prisma ./prisma
COPY lib ./lib
COPY workers/email-worker.ts ./workers/
COPY tsconfig.json ./
COPY tsconfig.worker.json ./

RUN npx prisma generate
RUN npm install -g typescript ts-node

CMD ["ts-node", "--project", "tsconfig.worker.json", "workers/email-worker.ts"]